name: Container Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build-and-push:
    name: Build and push to quay.io
    runs-on: ubuntu-latest

    steps:
    - name: git checkout
      uses: actions/checkout@v2
      
    - name: git checkout netron code
      uses: actions/checkout@v2
      with:
        repository: lutzroeder/netron
        path: ./app-src

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Quay
      uses: docker/login-action@v1
      with:
        registry: quay.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build the container image and push it
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          quay.io/jasonredhat/netron:latest
